source package.env
echo -n "FROM ${PACKAGE_CONTAINER_BASE}
WORKDIR ${PACKAGE_CONTAINER_WORKDIR}
COPY ${PACKAGE_CONTAINER_APPLICATION}-${1} ${PACKAGE_CONTAINER_DESTINATION}${PACKAGE_CONTAINER_APPLICATION}
LABEL org.opencontainers.image.source ${PACKAGE_CONTAINER_SOURCE}
LABEL org.opencontainers.image.licenses ${PACKAGE_CONTAINER_LICENSE}
ENTRYPOINT [\"${PACKAGE_CONTAINER_APPLICATION}\"]" >Dockerfile